import Head from "next/head"
import Wrapper from "@components/supports/[pid]/Wrapper"
import { Box, Flex } from "@components/commons"
import ImageWrapper from "@components/imageWrapper"
export default function Support() {
  return (
    <>
      <Head>
        <title>Supports</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Wrapper>
        <Flex sx={{ flexWrap: "wrap", justifyContent: "space-between" }}>
          <Box sx={{ width: "calc((100% + 16px)/12*7 - 16px)" }}>
            <ImageWrapper
              brProps="8px"
              src={
                "https://public.nftstatic.com/static/nft/webp/nft-extdata-loader/S3/1687117348836_qisaf0n3f5cs35v6e73o0x7kmkxh7rm7_400x400.webp"
              }
              wrapperClassName="lazy-load-image-wrapper"
              effect="blur"
              wrapperProps={{
                style: {
                  display: "flex",
                  width: "100%",
                  height: "100%",
                  borderRadius: "8px",
                  border: "0px solid",
                },
              }}
              style={{
                borderRadius: "8px",
                objectFit: "contain",
              }}
            />
          </Box>
          <Box sx={{ width: "calc((100% + 16px)*.375 - 8px)" }}></Box>
        </Flex>
      </Wrapper>
    </>
  )
}
