import Head from "next/head"
import { Box, Flex } from "@components/commons"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { SupportCard, SkeletonSupportCard } from "@components/profile"
const inter = Inter({ subsets: ["latin"] })
export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Box
          sx={{
            maxWidth: "1260px",
            width: "100%",
            margin: "auto",
            px: ["12px", "30px"],
          }}
        >
          <Box
            sx={{
              width: "100%",
              height: "100%",
              position: "relative",
              overflow: "hidden",
            }}
          >
            <Box
              sx={{
                width: "100%",
                display: ["flex", "grid"],
                flexDirection: "column",
                gap: ["8px", "24px"],
                gridTemplateColumns: "repeat(4, calc(25% - 20px))",
              }}
            >
              <SupportCard
                maker={"현대해상화재보험"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
              />
              <SupportCard
                maker={"현대해상화재보험"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
              />
              <SupportCard
                maker={"현대해상화재보험"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
              />
              <SupportCard
                maker={"현대해상화재보험"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
              />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
            </Box>
          </Box>
        </Box>
      </main>
    </>
  )
}
