import Head from "next/head"
import { Box, Flex } from "@components/commons"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { SupportCard, SkeletonSupportCard } from "@components/profile"
import UserInfo from "@components/profile/user-info"
import Tabs from "@components/commons/Tabs/tabs"
const inter = Inter({ subsets: ["latin"] })
export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Flex as="main" sx={{ flexDirection: "column", flex: 1 }}>
        <Box sx={{ pb: [0, "80px"] }}>
          <Box sx={{ maxWidth: "1260px", mx: "auto", pb: ["24px", "77px"] }}>
            <UserInfo />
          </Box>
        </Box>

        <Box
          sx={{
            maxWidth: "1260px",
            width: "100%",
            margin: "auto",
            px: ["12px", "30px"],
          }}
        >
          {/* <Tabs defaultActiveKey="hi" variant="container">
            <Box>테스트</Box>
          </Tabs> */}
          {/* Tabs */}

          <Flex
            __css={{
              alignItems: "center",
              justifyContent: "",
              borderBottom: "1px solid",
              borderColor: "black30",
              mb: 7,
            }}
          >
            <Box __css={{ position: "relative", width: "100%" }}>
              <Flex
                __css={{
                  flexDirection: "row",
                  overflow: "scroll",
                  whiteSpace: "nowrap",
                  width: "100%",
                  gap: ["0", "24px"],
                }}
                sx={{ mt: 8 }}
              >
                {/* Tab */}
                <Box
                  __css={{ cursor: "pointer", minWidth: "auto", flex: [1, 0] }}
                >
                  <Box
                    __css={{
                      userSelect: "none",
                      lineHeight: "20px",
                      fontWeight: "medium",
                      py: 3,
                      px: 2,
                      color: "black90",
                      boxShadow: "selectedTab",
                      textAlign: "center",
                    }}
                  >
                    서포터 목록
                  </Box>
                </Box>
                <Box
                  __css={{ cursor: "pointer", minWidth: "auto", flex: [1, 0] }}
                >
                  <Box
                    __css={{
                      userSelect: "none",
                      lineHeight: "20px",
                      fontWeight: "medium",
                      py: 3,
                      px: 2,
                      color: "black50",
                      textAlign: "center",
                    }}
                  >
                    활동내역
                  </Box>
                </Box>
              </Flex>
            </Box>
          </Flex>
          <Box
            sx={{
              width: "100%",
              height: "100%",
              position: "relative",
              overflow: "hidden",
            }}
          >
            <Box
              sx={{
                width: "100%",
                display: ["flex", "grid"],
                flexDirection: "column",
                gap: ["8px", "24px"],
                gridTemplateColumns: "repeat(4, calc(25% - 20px))",
              }}
            >
              <SupportCard
                href="/supports/mint/1"
                maker={"현대해상화재보험"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
              />
              <SupportCard
                href="/supports/mint/1"
                maker={"현대해상화재보험"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
              />
              <SupportCard
                maker={"현대해상화재보험"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                href="/supports/mint/1"
              />
              <SupportCard
                maker={"현대해상화재보험"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                href="/supports/mint/1"
              />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
            </Box>
          </Box>
        </Box>
      </Flex>
    </>
  )
}
