import Head from "next/head"
import { Box, Flex } from "@components/commons"
import { SupportCard, SkeletonSupportCard } from "@components/profile"
import UserInfo from "@components/profile/user-info"
import { TabsContainer, Tab, TabList, Panel } from "@components/commons/Tabs/tab"
export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Flex as="main" sx={{ flexDirection: "column", flex: 1 }}>
        <Box sx={{ pb: [0, "80px"] }}>
          <Box sx={{ maxWidth: "1260px", mx: "auto", pb: ["24px", "77px"], pt: ["72px"] }}>
            <UserInfo />
          </Box>
        </Box>

        <Box
          sx={{
            maxWidth: "1260px",
            width: "100%",
            mx: "auto",
            px: ["12px", "30px"],
          }}
        >
          {/* <Tabs defaultActiveKey="hi" variant="container">
            <Box>테스트</Box>
          </Tabs> */}
          {/* Tabs */}
          <TabsContainer defaultActiveKey={"supports"}>
            <TabList tabsSx={{ mb: 7 }} variant="standard">
              <Tab tabKey="supports">서포트 목록</Tab>
              <Tab tabKey="activity">활동내역</Tab>
            </TabList>
            <Box
              sx={{
                width: "100%",
                height: "100%",
                position: "relative",
                overflow: "hidden",
              }}
            >
              <Panel tabKey="supports">
                <Box
                  sx={{
                    width: "100%",
                    display: ["flex", "grid"],
                    flexDirection: "column",
                    gap: ["8px", "24px"],
                    gridTemplateColumns: "repeat(4, calc(25% - 20px))",
                  }}
                >
                  <SupportCard
                    href="/supports/mint/1"
                    maker={"현대해상화재보험"}
                    name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                  />
                  <SupportCard
                    href="/supports/mint/1"
                    maker={"현대해상화재보험"}
                    name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                  />
                  <SupportCard
                    maker={"현대해상화재보험"}
                    name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                    href="/supports/mint/1"
                  />
                  <SupportCard
                    maker={"현대해상화재보험"}
                    name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                    href="/supports/mint/1"
                  />
                  <SkeletonSupportCard />
                  <SkeletonSupportCard />
                  <SkeletonSupportCard />
                  <SkeletonSupportCard />
                  <SkeletonSupportCard />
                </Box>
              </Panel>
            </Box>
          </TabsContainer>
        </Box>
      </Flex>
    </>
  )
}
