import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { Box, Flex } from "@components/commons"
import ImageWrapper from "@components/imageWrapper"
import Link from "next/link"
import CardImageWrapper from "@components/profile/card-image-wrapper"
import { LuUser } from "react-icons/lu"
import { SupportCard } from "@components/profile"
import Skeleton from "@components/commons/Skeleton"
import SkeletonSupportCard from "@components/profile/skeleton-support-card"
import LogoSmall from "@/assets/icons/logo-small"
import Logo from "../../public/logosmall.svg"
import { TabsContainer, TabList, Tab } from "@components/commons/Tabs/tab"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Box>gkdl</Box>
        <TabsContainer defaultActiveKey={"namba1"}>
          <TabList tabsSx={{ mt: 8 }} variant="standard">
            <Tab tabKey="namba1">남바완</Tab>
            <Tab tabKey="namba2">남바투</Tab>
          </TabList>
        </TabsContainer>
      </div>
    </>
  )
}
