import Head from "next/head"
import { Box, Flex, Avatar, Button, Skeleton } from "@components/commons"
import ImageWrapper from "@components/imageWrapper"
import { Instagram, Twitter, Chrome, Plus, Share2, MoreVertical } from "lucide-react"
import MoreContents from "@components/more-contents"
import { SkeletonSupportCard } from "@components/supports"
import { GetServerSideProps } from "next"
import axios from "axios"
import { useQuery } from "@tanstack/react-query"
import { Tab, TabsContainer, TabList, Panel } from "@components/commons/Tabs/tab"
export default function Maker({ pid }: any) {
  const fetchMaker = async () => {
    if (pid) {
      const res = await axios.get(`/api/makers/info/${pid}`)
      const result = res.data

      return result
      //
    }
  }
  const { data, isLoading, error } = useQuery({ queryKey: ["maker", pid], queryFn: fetchMaker })

  console.log(data)
  return (
    <>
      {/* <Head>
        <title>Makers</title>
        <meta name="description" content="Generated by create next app" />
      </Head> */}
      <Flex
        as="main"
        sx={{
          flexDirection: "column",
          minHeight: "100vh",
          alignItems: "center",
          marginTop: "-64px",
        }}
      >
        <Box sx={{ pb: "64px", width: "100%" }}>
          <Box
            sx={{
              position: "relative",
              maxHeight: "434px",
              overflow: "hidden",
            }}
          >
            <ImageWrapper
              pb={["40%", "30%"]}
              src={data && data.banner}
              // src="https://i.seadn.io/gcs/files/cf29f66e5492c40bd190d6e858521e4f.jpg?auto=format&dpr=1&w=3840"
              wrapperClassName="lazy-load-image-wrapper"
              effect="blur"
              wrapperProps={{
                style: {
                  width: "100%",
                  height: "100%",
                },
              }}
              style={{
                objectFit: "cover",
                width: "100%",
                height: "100%",
              }}
            />
          </Box>
          <Box sx={{ width: "100%", pl: 4, maxWidth: "1200px", mx: "auto" }}>
            <Box sx={{ mt: "-80px", mb: 5 }}>
              <Box
                sx={{
                  width: ["104px", "200px"],
                  height: ["104px", "200px"],
                  position: "relative",
                  border: "8px solid #fff",
                  boxShadow: "shadow3",
                  borderRadius: "50%",
                  overflow: "hidden",
                }}
              >
                <ImageWrapper
                  pb={100}
                  src={data && data.profileImage}
                  wrapperClassName="lazy-load-image-wrapper"
                  effect="blur"
                  wrapperProps={{
                    style: {
                      width: "100%",
                      height: "100%",
                    },
                  }}
                  style={{
                    objectFit: "cover",
                    width: "100%",
                    height: "100%",
                  }}
                />
              </Box>
            </Box>
          </Box>
          <Box sx={{ width: "100%", maxWidth: "1200px", mx: "auto", px: 3 }}>
            <Flex sx={{ justifyContent: "space-between" }}>
              <Box
                sx={{
                  fontSize: "32px",
                  lineHeight: "40px",
                  fontWeight: "bold",
                }}
              >
                {data ? <>{data.name}</> : <Skeleton sx={{ height: "40px", minWidth: "276px" }} radius="4px" />}
              </Box>
              <Flex sx={{ alignItems: "center", display: ["none", "block"] }}>
                {/* <Flex sx={{ alignItems: "center", mr: 4 }}>
                  <Button sx={{ px: 4, borderRadius: "12px" }}>
                    <Plus size={18} />
                    <Box sx={{ px: 1 }}>Join</Box>
                  </Button>
                </Flex> */}
                <Flex sx={{ alignItems: "center" }}>
                  <Button sx={{ bg: "transparent", border: "none" }}>
                    <Twitter size={24} />
                  </Button>
                  <Button sx={{ bg: "transparent", border: "none" }}>
                    <Instagram size={24} />
                  </Button>
                  <Button sx={{ bg: "transparent", border: "none" }}>
                    <Chrome size={24} />
                  </Button>
                  <Button sx={{ bg: "transparent", border: "none" }}>
                    <Share2 size={24} />
                  </Button>
                  <Button sx={{ bg: "transparent", border: "none" }}>
                    <MoreVertical size={24} />
                  </Button>
                </Flex>
              </Flex>
              <Flex sx={{ alignItems: "center", display: ["block", "none"] }}>
                <Button sx={{ bg: "transparent", border: "none" }}>
                  <Share2 size={20} />
                </Button>
                <Button sx={{ bg: "transparent", border: "none" }}>
                  <MoreVertical size={20} />
                </Button>
              </Flex>
            </Flex>

            <Flex sx={{ maxWidth: "776px" }}>
              {data ? (
                <MoreContents
                  contents={data.description}
                  line={3}
                  boxSx={{
                    fontSize: 1,
                    lineHeight: "1.5",
                    minHeight: "36px",
                    color: "black70",
                  }}
                />
              ) : (
                <Box sx={{ pt: 4, width: "100%", gap: "14px", display: "flex", flexDirection: "column" }}>
                  <Skeleton sx={{ height: "15px", width: "70%" }} />
                  <Skeleton sx={{ height: "15px", width: "90%" }} />
                </Box>
              )}
            </Flex>
            <TabsContainer defaultActiveKey={"supports"}>
              <TabList tabsSx={{ mt: 8 }} variant="standard">
                <Tab tabKey="supports">서포트 목록</Tab>
                <Tab tabKey="members">맴버 목록</Tab>
              </TabList>

              <Panel tabKey="supports">
                <Box
                  sx={{
                    width: "100%",
                    height: "100%",
                    position: "relative",
                    overflow: "hidden",
                  }}
                >
                  <Box
                    sx={{
                      width: "100%",
                      display: ["flex", "grid"],
                      flexDirection: "column",
                      gap: ["8px", "24px"],
                      gridTemplateColumns: "repeat(4, calc(25% - 18px))",
                      pt: 3,
                    }}
                  >
                    {/* <SupportCard
                  category="임영웅"
                  maker={"임영웅 영웅시대"}
                  name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                  supports={12}
                />
                <SupportCard
                  category="임영웅"
                  maker={"임영웅 영웅시대"}
                  name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                  supports={12}
                />{" "}
                <SupportCard
                  category="임영웅"
                  maker={"임영웅 영웅시대"}
                  name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                  supports={12}
                />{" "}
                <SupportCard
                  category="임영웅"
                  maker={"임영웅 영웅시대"}
                  name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                  supports={12}
                />{" "}
                <SupportCard
                  category="임영웅"
                  maker={"임영웅 영웅시대"}
                  name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                  supports={12}
                /> */}
                    <SkeletonSupportCard />
                    <SkeletonSupportCard />
                    <SkeletonSupportCard />
                    <SkeletonSupportCard />
                  </Box>
                </Box>
              </Panel>
            </TabsContainer>
          </Box>
        </Box>
      </Flex>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async context => {
  console.log("server side")

  const { pid } = context.query
  console.log(pid)
  return {
    props: {
      pid,
    },
  }
}
