import Head from "next/head"
import { Box, Flex, Avatar, Button } from "@components/commons"
import ImageWrapper from "@components/imageWrapper"
import ListIcon from "@icons/list-icons"
import Link from "next/link"
import { LuYoutube, LuInstagram, LuTwitter } from "react-icons/lu"
import { Instagram, Twitter, Chrome, Plus, Zap } from "lucide-react"
import MoreContents from "@components/more-contents"
import WrapBox from "../component/wrap-box"
import Tabs from "@components/commons/Tabs/tabs"
export default function Maker() {
  return (
    <>
      {/* <Head>
        <title>Makers</title>
        <meta name="description" content="Generated by create next app" />
      </Head> */}
      <Flex
        as="main"
        sx={{
          flexDirection: "column",
          minHeight: "100vh",
          alignItems: "center",
        }}
      >
        <Box sx={{ pb: "64px", width: "100%" }}>
          <Box
            sx={{
              position: "relative",
              maxHeight: "320px",
              overflow: "hidden",
            }}
          >
            <ImageWrapper
              pb={25}
              src="https://i.seadn.io/gcs/files/cf29f66e5492c40bd190d6e858521e4f.jpg?auto=format&dpr=1&w=3840"
              wrapperClassName="lazy-load-image-wrapper"
              effect="blur"
              wrapperProps={{
                style: {
                  width: "100%",
                  height: "100%",
                },
              }}
              style={{
                objectFit: "cover",
                width: "100%",
                height: "100%",
              }}
            />
          </Box>
          <Box sx={{ width: "100%", pl: 4, maxWidth: "1200px", mx: "auto" }}>
            <Box sx={{ mt: "-160px", mb: 4 }}>
              <Box
                sx={{
                  width: "200px",
                  height: "200px",
                  position: "relative",
                  border: "8px solid #fff",
                  boxShadow: "shadow3",
                  borderRadius: "50%",
                  overflow: "hidden",
                }}
              >
                <ImageWrapper
                  pb={100}
                  src="https://i.seadn.io/gcs/files/d6d3ef940fb05d2b946157c663b5fb78.gif?auto=format&dpr=1&w=3840"
                  wrapperClassName="lazy-load-image-wrapper"
                  effect="blur"
                  wrapperProps={{
                    style: {
                      width: "100%",
                      height: "100%",
                    },
                  }}
                  style={{
                    objectFit: "cover",
                    width: "100%",
                    height: "100%",
                  }}
                />
              </Box>
            </Box>
          </Box>
          <Box sx={{ width: "100%", maxWidth: "1200px", mx: "auto", px: 3 }}>
            <Flex sx={{ justifyContent: "space-between" }}>
              <Box
                sx={{
                  fontSize: "32px",
                  lineHeight: "40px",
                  fontWeight: "bold",
                }}
              >
                영웅시대 HERO
              </Box>
              <Flex sx={{ alignItems: "center" }}>
                <Flex sx={{ alignItems: "center", mr: 4 }}>
                  <Button sx={{ px: 4, borderRadius: "12px" }}>
                    <Plus size={18} />
                    <Box sx={{ px: 1 }}>Join</Box>
                  </Button>
                </Flex>
                <Flex sx={{ alignItems: "center" }}>
                  <Button sx={{ bg: "transparent", border: "none" }}>
                    <Twitter size={24} />
                  </Button>
                  <Button sx={{ bg: "transparent", border: "none" }}>
                    <Instagram size={24} />
                  </Button>
                  <Button sx={{ bg: "transparent", border: "none" }}>
                    <Chrome size={24} />
                  </Button>
                </Flex>
              </Flex>
            </Flex>
            <Flex sx={{ pt: 2 }}>
              <Flex
                sx={{
                  bg: "#6c707b",
                  px: 2,
                  pb: "6px",
                  pt: 1,
                  borderRadius: "12px",
                  color: "#fff",
                  display: "inline-flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontSize: 1,
                }}
              >
                <Box sx={{ lineHeight: "20px", pl: 1 }}>#</Box>
                <Box sx={{ px: 1, lineHeight: "20px" }}>임영웅</Box>
              </Flex>
            </Flex>
            <Flex sx={{ maxWidth: "720px" }}>
              <MoreContents
                contents={
                  "신세계백화점의 대표 캐릭터 푸빌라의 친구들입니다. 붉은 털 여우 “깨또“, 귀여운 너구리 “후트“, 작고 날 쌘 다람쥐 “포코“입니다. 각기 다른 매력을 뽐내는 푸빌라의 유쾌한 친구들을 만나볼까요? 긍정적 분위기, 훌륭한 커뮤니티가 구축되고 있습니다. \n They are friends of Puuvilla, the representative character of Shinsegae Department Store. It’s a red-haired fox ‘kettu’, a cute raccoon “hut”, and a small sharp squirrel, “Poco”. Let’s meet the fun friends of Puuvilla a who show off their different charms A positive atmosphere, a great community is being built."
                }
                line={2}
                boxSx={{
                  fontSize: 1,
                  lineHeight: "1.5",
                  minHeight: "36px",
                  color: "black70",
                }}
              />
            </Flex>
            <Flex
              sx={{
                flexWrap: "wrap",
                pt: 5,
                gap: "40px",
                flexDirection: "row",
              }}
            >
              <WrapBox name={"members"} value={"12.7k"} />
              <WrapBox name={"supports"} value={"83"} />
              <WrapBox name={"badges"} value={"3.72k"} />
              <WrapBox name={"owners"} value={"903"} />
              <WrapBox name={"created"} value={"May 2023"} />
            </Flex>
            <Flex
              __css={{
                alignItems: "center",
                justifyContent: "",
                borderBottom: "1px solid",
                borderColor: "black30",
              }}
            >
              {/* Tabs */}
              <Box __css={{ position: "relative" }}>
                <Flex
                  __css={{
                    flexDirection: "row",
                    overflow: "scroll",
                    whiteSpace: "nowrap",
                    width: "100%",
                    gap: "24px",
                  }}
                  sx={{ mt: 8 }}
                >
                  {/* Tab */}
                  <Box __css={{ cursor: "pointer", minWidth: "auto" }}>
                    <Box
                      __css={{
                        userSelect: "none",
                        lineHeight: "20px",
                        fontWeight: "medium",
                        py: 3,
                        px: 2,
                        color: "black90",
                        boxShadow: "selectedTab",
                      }}
                    >
                      홈
                    </Box>
                  </Box>
                  <Box __css={{ cursor: "pointer", minWidth: "auto" }}>
                    <Box
                      __css={{
                        userSelect: "none",
                        lineHeight: "20px",
                        fontWeight: "medium",
                        py: 3,
                        px: 2,
                        color: "black50",
                      }}
                    >
                      서포터
                    </Box>
                  </Box>
                  <Box __css={{ cursor: "pointer", minWidth: "auto" }}>
                    <Box
                      __css={{
                        userSelect: "none",
                        lineHeight: "20px",
                        fontWeight: "medium",
                        py: 3,
                        px: 2,
                        color: "black50",
                      }}
                    >
                      맴버
                    </Box>
                  </Box>
                  <Box __css={{ cursor: "pointer", minWidth: "auto" }}>
                    <Box
                      __css={{
                        userSelect: "none",
                        lineHeight: "20px",
                        fontWeight: "medium",
                        py: 3,
                        px: 2,
                        color: "black50",
                      }}
                    >
                      커뮤니티
                    </Box>
                  </Box>
                </Flex>
              </Box>
            </Flex>
            <Tabs defaultActiveKey="hi" variant="container">
              <Box>테스트</Box>
            </Tabs>
          </Box>
        </Box>
      </Flex>
    </>
  )
}
