import Head from "next/head"
import { useState } from "react"
import { Avatar, Box, Flex, Selector } from "@components/commons"
import MakerCard from "@components/makers/maker-card"
export default function Makers() {
  const [order, setOrder] = useState<string>("lastest")

  const onChangeOrder = (newOrder: string) => {
    if (newOrder !== order) {
      setOrder(newOrder)
      // mutation.mutate(category[activeTab].baseUrl)
    }
  }

  return (
    <>
      <Head>
        <title>Makers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Flex
        as="main"
        sx={{
          flexDirection: "column",
          minHeight: "100vh",
          alignItems: "center",
          py: 8,
        }}
      >
        {/* Banner */}
        <Flex
          sx={{ flexDirection: "column", alignItems: "center", pb: [6, 12] }}
        >
          <Box
            sx={{
              fontSize: ["32px", "72px"],
              fontWeight: "bold",
              lineHeight: ["40px", "80px"],
              pb: [3, 6],
            }}
          >
            Supoer Makers
          </Box>
          <Box sx={{ fontSize: ["14px", "16px"] }}>
            멋진 서포터를 만드는 메이커들을 만나 보세요. 당신과 함께 할 멋진
            메이커들
          </Box>
        </Flex>
        <Box
          __css={{
            maxWidth: "1260px",
            width: "100%",
            marginX: "auto",
            px: ["12px", "30px"],
          }}
        >
          <Flex direction={"row-reverse"} pb="4">
            <Selector
              options={[
                { content: "인기 순", key: "popular" },
                { content: "최근 순", key: "lastest" },
              ]}
              value={order} //초기값됴
              onChange={onChangeOrder}
              sx={{
                fontSize: [1, 2],
                lineHeight: "26px",
                padding: "6px 12px",
                color: "black90",
                width: ["96px", "120px"],
                height: ["32px", "40px"],
              }}
            />
          </Flex>
        </Box>
        <Box
          sx={{
            maxWidth: "1260px",
            width: "100%",
            marginX: "auto",
            px: ["12px", "30px"],
          }}
        >
          <Box
            sx={{
              width: "100%",
              height: "100%",
              position: "relative",
              overflow: "hidden",
            }}
          >
            <Box
              sx={{
                width: "100%",
                display: ["flex", "grid"],
                flexDirection: "column",
                gap: ["8px", "24px"],
                gridTemplateColumns: "repeat(3, calc(33.3% - 17px))",
                pt: 3,
              }}
            >
              {/* 1 maker */}
              <MakerCard />
              <MakerCard />
              <MakerCard />
              <MakerCard />
            </Box>
          </Box>
        </Box>
      </Flex>
    </>
  )
}
