import Head from "next/head"
import { Inter } from "next/font/google"
import styles from "@styles/Home.module.css"

import { Box, Flex } from "@components/commons"
import { SkeletonSupportCard, SupportCard } from "@components/supports"

const inter = Inter({ subsets: ["latin"] })
export default function Supports() {
  return (
    <>
      <Head>
        <title>Supports</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* <link rel="icon" href="/favicon.ico" /> */}
      <Box
        as="main"
        sx={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
          alignItems: "center",
          py: 8,
        }}
      >
        <Flex
          sx={{ flexDirection: "column", alignItems: "center", pb: [6, 12] }}
        >
          <Box
            sx={{
              fontSize: ["32px", "72px"],
              fontWeight: "bold",
              lineHeight: ["40px", "80px"],
              pb: [3, 6],
            }}
          >
            Love & Action
          </Box>
          <Box sx={{ fontSize: ["14px", "16px"] }}>
            당신의 사랑을 표현하고 행동해 보세요
          </Box>
        </Flex>
        <Box
          sx={{
            maxWidth: "1260px",
            width: "100%",
            margin: "auto",
            px: ["12px", "30px"],
          }}
        >
          <Box
            sx={{
              width: "100%",
              height: "100%",
              position: "relative",
              overflow: "hidden",
            }}
          >
            <Box
              sx={{
                width: "100%",
                display: ["flex", "grid"],
                flexDirection: "column",
                gap: ["8px", "24px"],
                gridTemplateColumns: "repeat(4, calc(25% - 18px))",
                pt: 3,
              }}
            >
              <SupportCard
                category="임영웅"
                maker={"임영웅 영웅시대"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                supports={12}
              />
              <SupportCard
                category="임영웅"
                maker={"임영웅 영웅시대"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                supports={12}
              />{" "}
              <SupportCard
                category="임영웅"
                maker={"임영웅 영웅시대"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                supports={12}
              />{" "}
              <SupportCard
                category="임영웅"
                maker={"임영웅 영웅시대"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                supports={12}
              />{" "}
              <SupportCard
                category="임영웅"
                maker={"임영웅 영웅시대"}
                name={"임영웅 2022 'IM HERO'콘서트 잠실 주 경기장 대관 후원"}
                supports={12}
              />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
              <SkeletonSupportCard />
            </Box>
          </Box>
        </Box>
      </Box>
    </>
  )
}
