import React, { useState, useRef } from "react"
// import { useRouter } from 'next/router'
import Head from "next/head"
import {
  Avatar,
  Button,
  Flex,
  Text,
  Box,
  Textarea,
  TextField,
} from "@components/commons"
// import { userCheckLogin, userLogin } from '@pages/api/user/use-login'
// import Google from '@assets/icons/Google'

export default function Mypage() {
  const usernameRef = useRef(null)
  const websiteRef = useRef(null)
  const instagramRef = useRef(null)
  const facebookRef = useRef(null)
  const twitterRef = useRef(null)
  const [userName, setUserName] = useState<string>("조쿠나조아")
  // const [intro, setIntro] = useState<string>('')
  return (
    <>
      <Head>
        <title>테스토</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Flex as="main" sx={{ flexDirection: "column", flex: 1 }}>
        <Box backgroundColor={""}>
          {/* background */}
          <Box
            sx={{
              maxWidth: "860px",
              width: "100%",
              mx: "auto",
              my: "64px",
              px: "30px",
            }}
          >
            <Flex
              sx={{
                fontSize: ["24px", "40px"],
                fontWeight: "bold",
                lineHeight: ["32px", "52px"],
              }}
            >
              {/* Title */}
              마이 프로필 수정
            </Flex>
            <Box mt={["32px", "64px"]}>
              <Flex direction={"row"} mb="10">
                <Avatar
                  size="120px"
                  src="https://public.nftstatic.com/static/nft/webp/nft-extdata-loader/S3/1687117348836_qisaf0n3f5cs35v6e73o0x7kmkxh7rm7_400x400.webp"
                />
                <Flex direction={"column"} ml="10" justify={"center"}>
                  <Text sx={{ fontWeight: "bold" }}>조쿠나조아</Text>
                  <Flex
                    mt={["2", "4"]}
                    sx={{ flexDirection: ["column", "row"] }}
                  >
                    <Flex mr={["0", "8"]} align={"center"}>
                      {/* <Google boxSize={[14,20]}/> */}
                      <Text ml="2">hyuk8181@gmail.com</Text>
                    </Flex>
                    <Flex mr={["0", "8"]} align={"center"}>
                      {/* <Google boxSize={[14,20]}/> */}
                      <Text ml="2">0X123SD…FHT5769</Text>
                    </Flex>
                  </Flex>
                </Flex>
              </Flex>
              <Flex direction={"column"} mb="10">
                <Text sx={{ fontWeight: "bold", mb: 2 }}>유저 네임</Text>
                <Text sx={{ color: "black50" }}>
                  사이트 내에 표출되는 나의 이름입니다.
                  <br></br>
                  개인정보보호를 위해 실명이 아닌 닉네임 기재를 권장드립니다.
                </Text>
                <Box mt="2" sx={{ width: "100%" }}>
                  <TextField
                    ref={usernameRef}
                    value={userName}
                    // variant="line"
                    boxProps={{
                      sx: {
                        width: "100%",
                        borderWidth: "2px",
                        borderRadius: "8px",
                        height: ["40px", "48px"],
                      },
                    }}
                    sx={{ fontWeight: "bold" }}
                  />
                  <Flex justify={"flex-end"} mr="2" mt="2">
                    <Text color="black50" sx={{ fontSize: [0, 1] }}>
                      5 / 20
                    </Text>
                  </Flex>
                </Box>
              </Flex>
              <Flex direction={"column"} mb="10">
                <Text sx={{ fontWeight: "bold", mb: 2 }}>프로필 이미지</Text>
                <Text color="black.50">
                  사이트 내에 표출되는 내 프로필 이미지입니다.
                  <br></br>
                  1000px x 1000px JPG, PNG 지원합니다. 최대 10MB 까지 업로드
                  가능합니다.
                </Text>
                <Flex mt="4" align={"center"}>
                  <Avatar
                    size="64px"
                    src="https://public.nftstatic.com/static/nft/webp/nft-extdata-loader/S3/1687117348836_qisaf0n3f5cs35v6e73o0x7kmkxh7rm7_400x400.webp"
                  />
                  <Box ml="6">
                    <Button
                      //   size={["sm", "md"]}
                      sx={{
                        boxShadow: "floody2",
                        boxSizing: "border-box",
                        minHeight: ["32px", "40px"],
                        fontSize: [1, 2],
                      }}
                    >
                      변경하기
                    </Button>
                  </Box>
                </Flex>
              </Flex>
              <Flex direction={"column"} mb="10">
                <Text sx={{ fontWeight: "bold", mb: 2 }}>간단 소개글 작성</Text>
                <Text color="black50">
                  마이 페이지에 들어갈 간단한 소개글을 작성해주세요.
                </Text>
                <Flex direction={"column"} mt="2" sx={{ width: "100%" }}>
                  <Textarea
                    sx={{
                      resize: "vertical",
                      fontSize: [0, 1, 2],
                      minHeight: "240px",
                    }}
                    // variant={"outline"}
                    placeholder="최대 200자 이내로 작성해주세요."
                  />
                  <Flex justify={"flex-end"} mr="2" mt="2">
                    <Text color="black50" sx={{ fontSize: [0, 1] }}>
                      0 / 200
                    </Text>
                  </Flex>
                </Flex>
              </Flex>
              <Flex direction={"column"} mb={["6", "10"]}>
                <Text sx={{ fontWeight: "bold", mb: 2 }}>내 SNS 링크 설정</Text>
                <Box mt="2">
                  <Box sx={{ width: "full", mb: 6 }}>
                    <Flex
                      sx={{
                        fontSize: [0, 1],
                        color: "black50",
                        lineHeight: "20px",
                        mb: 2,
                        ml: 1,
                      }}
                    >
                      웹사이트
                    </Flex>
                    <TextField
                      id="website"
                      //   variant={"line"}
                      boxProps={{
                        sx: {
                          width: "100%",
                          borderWidth: "2px",
                          borderRadius: "8px",
                          height: ["40px", "48px"],
                        },
                      }}
                      ref={websiteRef}
                    />
                  </Box>
                  <Box sx={{ width: "full", mb: 6 }}>
                    <Flex
                      sx={{
                        fontSize: [0, 1],
                        color: "black50",
                        lineHeight: "20px",
                        mb: 2,
                        ml: 1,
                      }}
                    >
                      인스타그램
                    </Flex>
                    <TextField
                      id="instagram"
                      //   variant={"line"}
                      boxProps={{
                        sx: {
                          width: "100%",
                          borderWidth: "2px",
                          borderRadius: "8px",
                          height: ["40px", "48px"],
                        },
                      }}
                      ref={websiteRef}
                    />
                  </Box>
                  <Box sx={{ width: "full", mb: 6 }}>
                    <Flex
                      sx={{
                        fontSize: [0, 1],
                        color: "black50",
                        lineHeight: "20px",
                        mb: 2,
                        ml: 1,
                      }}
                    >
                      페이스북
                    </Flex>
                    <TextField
                      id="facebook"
                      //   variant={"line"}
                      boxProps={{
                        sx: {
                          width: "100%",
                          borderWidth: "2px",
                          borderRadius: "8px",
                          height: ["40px", "48px"],
                        },
                      }}
                      ref={websiteRef}
                    />
                  </Box>
                  <Box sx={{ width: "full", mb: 6 }}>
                    <Flex
                      sx={{
                        fontSize: [0, 1],
                        color: "black50",
                        lineHeight: "20px",
                        mb: 2,
                        ml: 1,
                      }}
                    >
                      트위터
                    </Flex>
                    <TextField
                      id="twitter"
                      //   variant={"line"}
                      boxProps={{
                        sx: {
                          width: "100%",
                          borderWidth: "2px",
                          borderRadius: "8px",
                          height: ["40px", "48px"],
                        },
                      }}
                      ref={websiteRef}
                    />
                  </Box>
                </Box>
              </Flex>
              <Flex justify={"flex-end"}>
                <Button
                  //   variant={"solid"}
                  sx={{
                    minHeight: ["40px", "48px"],
                    minWidth: ["100%", "176px"],
                    boxShadow: "floody2",
                    bg: "main50",
                    color: "#fff",
                  }}
                >
                  변경 저장하기
                </Button>
              </Flex>
            </Box>
          </Box>
        </Box>
      </Flex>
    </>
  )
}

// export async function getServerSideProps(context) {
//     // const res = await userCheckLogin(context.req.headers.cookie);
//     // console.log(res);
//     // return {
//     //     props: {isLoggedIn: true}
//     // }
// }
